[package]
name = "make-a-number"
version = "0.1.0"
edition = "2021"

[lib]
name = "saveit"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "1.3.0", features = ["derive"] }
solana-program = "1.17.13"

[dev-dependencies]
solana-program-test = "1.17.13"
solana-sdk = "1.17.13"
